baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "forty"


[Params]
  subtitle = "にゃーん"
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true